on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release --no-build
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=1.0.$GITHUB_RUN_NUMBER --no-build --output .
    - name: Push
      run: dotnet nuget push /home/runner/work/NumberTheory/NumberTheory/DeoEsor.NumberTheory.1.0.$GITHUB_RUN_NUMBER.nupkg --source https://nuget.pkg.github.com/acraven/index.json --api-key $GITHUB_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
